name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - project-x
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Install dependencies
        run: cd docs && npm install

      - name: Build app
        run: cd docs && npm run build

      - name: Add .nojekyll
        run: touch docs/dist/.nojekyll

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/dist
          keep_files: false
          commit_message: "Deploy static site to GitHub Pages"