name: Deploy static site to GitHub Pages

on:
  push:
    branches:
      - project-k
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # A fetch depth of 0 is needed for the deploy action

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs
          keep_files: true  # Keeps existing project folders
          destination_dir: project-k
          commit_message: "Deploy Project-K static site to GitHub Pages"
